name: Update_Blog
on:
  workflow_dispatch:
  schedule:
    - cron:  '0 * * * *'
permissions:
      contents: write
jobs:
  update-readme-with-blog:
    name: Update_Blog
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          comment_tag_name: "BLOG"
          feed_list: "https://blackscreenofdeath.medium.com/"
