name: Update_blog
on:
  schedule:
    # Runs at 00:00 UTC every day.
    - cron: "* * * * *"

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: JasonEtco/rss-to-readme@v1
        with:
          feed-url: https://blackscreenofdeath.medium.com/
          readme-section: feed
          max: 5
          template: "* [{{ title }}]({{ link }})"
